{% set group = "Billingegroup" %}
{% set name = "bg-mpl-stylesheets" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://github.com/{{ group }}/{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 85d1204a2214af3f438dad6967ff43d0aa63e5a068a45189482486b6ff34fbbb

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - matplotlib-base

test:
  imports:
    - bg_mpl_stylesheet

about:
  home: https://github.com/{{ group }}/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Defines a standardized matplotlib stylesheet for the Billinge Group'

extra:
  recipe-maintainers:
    - sbillinge
    - connorjbracy
